version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1883:1883/tcp"
    command: mosquitto -c /mosquitto-no-auth.conf

  server:
    build:
      context: .
    environment:
      - MQTT_HOST=mqtt
    ports:
      - "0.0.0.0:8000:8000/tcp"
